import { Scan } from '@/types/Scan';

export const sampleScans: Scan[] = [
  {
    id: '1',
    productName: 'Protein Bar',
    brand: 'FitLife',
    weight: '50g',
    scanDate: '2025-05-08',
    nutrition: {
      calories: 210,
      protein: 20,
      carbs: 15,
      sugar: 5,
      fat: 7,
      saturatedFat: 2,
      salt: 0.5,
    },
    ingredients: [
      {
        name: 'Whey Protein',
        description: 'High quality protein source',
        isAdditive: false,
      },
      { name: 'Almonds', description: 'Roasted nuts', isAdditive: false },
    ],
    additives: [
      {
        name: 'Soy Lecithin',
        code: 'E322',
        riskLevel: 'Good',
        purpose: 'Emulsifier',
      },
    ],
    positives: ['High protein', 'Low sugar'],
    negatives: ['Contains allergens'],
    cautions: ['May contain traces of peanuts'],
    fullIngredientsList: 'Whey Protein, Almonds, Soy Lecithin, Natural Flavors',
  },
  {
    id: '2',
    productName: 'Organic Juice',
    brand: 'NatureFresh',
    weight: '250ml',
    scanDate: '2025-05-07',
    nutrition: {
      calories: 110,
      protein: 1,
      carbs: 26,
      sugar: 22,
      fat: 0,
      saturatedFat: 0,
      salt: 0.05,
    },
    ingredients: [
      { name: 'Apple Juice', isAdditive: false },
      { name: 'Carrot Juice', isAdditive: false },
    ],
    additives: [],
    positives: ['Organic', 'No added sugar'],
    negatives: [],
    cautions: ['Refrigerate after opening'],
    fullIngredientsList: 'Apple Juice, Carrot Juice',
  },
  {
    id: '3',
    productName: 'Instant Noodles',
    brand: 'QuickBite',
    weight: '90g',
    scanDate: '2025-05-06',
    nutrition: {
      calories: 430,
      protein: 8,
      carbs: 55,
      sugar: 2,
      fat: 18,
      saturatedFat: 8,
      salt: 2.1,
    },
    ingredients: [
      { name: 'Wheat Flour', isAdditive: false },
      { name: 'Palm Oil', isAdditive: false },
    ],
    additives: [
      {
        name: 'Monosodium Glutamate',
        code: 'E621',
        riskLevel: 'Risky',
        purpose: 'Flavor enhancer',
        potentialEffects: 'Headaches, nausea',
      },
    ],
    positives: ['Quick meal'],
    negatives: ['High sodium', 'Contains additives'],
    cautions: ['Not recommended for frequent consumption'],
    fullIngredientsList: 'Wheat Flour, Palm Oil, Salt, Monosodium Glutamate',
  },
  {
    id: '4',
    productName: 'Greek Yogurt',
    brand: 'YummyDairy',
    weight: '150g',
    scanDate: '2025-05-05',
    nutrition: {
      calories: 100,
      protein: 10,
      carbs: 8,
      sugar: 6,
      fat: 2,
      saturatedFat: 1.5,
      salt: 0.1,
    },
    ingredients: [
      { name: 'Milk', isAdditive: false },
      {
        name: 'Live Cultures',
        description: 'Probiotic bacteria',
        isAdditive: false,
      },
    ],
    additives: [],
    positives: ['High protein', 'Probiotics'],
    negatives: [],
    cautions: ['Contains dairy'],
    fullIngredientsList: 'Milk, Live Cultures',
  },
  {
    id: '5',
    productName: 'Energy Drink',
    brand: 'BoostMax',
    weight: '330ml',
    scanDate: '2025-05-04',
    nutrition: {
      calories: 140,
      protein: 0,
      carbs: 34,
      sugar: 32,
      fat: 0,
      saturatedFat: 0,
      salt: 0.2,
    },
    ingredients: [
      { name: 'Carbonated Water', isAdditive: false },
      { name: 'Sugar', isAdditive: false },
    ],
    additives: [
      {
        name: 'Caffeine',
        riskLevel: 'Risky',
        purpose: 'Stimulant',
        potentialEffects: 'Increased heart rate',
      },
    ],
    positives: ['Boosts energy'],
    negatives: ['High sugar', 'Contains caffeine'],
    cautions: ['Not suitable for children and pregnant women'],
    fullIngredientsList: 'Carbonated Water, Sugar, Caffeine, Flavorings',
  },
  {
    id: '6',
    productName: 'Granola Cereal',
    brand: 'MorningCrunch',
    weight: '400g',
    scanDate: '2025-05-03',
    nutrition: {
      calories: 220,
      protein: 5,
      carbs: 30,
      sugar: 10,
      fat: 9,
      saturatedFat: 1,
      salt: 0.15,
    },
    ingredients: [
      { name: 'Oats', isAdditive: false },
      { name: 'Honey', isAdditive: false },
    ],
    additives: [],
    positives: ['High fiber', 'Good source of energy'],
    negatives: ['Moderate sugar content'],
    cautions: ['May contain nuts'],
    fullIngredientsList: 'Oats, Honey, Dried Fruits, Sunflower Oil',
  },
  {
    id: '7',
    productName: 'Chocolate Bar',
    brand: 'SweetTreats',
    weight: '100g',
    scanDate: '2025-05-02',
    nutrition: {
      calories: 550,
      protein: 7,
      carbs: 55,
      sugar: 45,
      fat: 35,
      saturatedFat: 20,
      salt: 0.2,
    },
    ingredients: [
      { name: 'Cocoa', isAdditive: false },
      { name: 'Milk Solids', isAdditive: false },
    ],
    additives: [
      {
        name: 'Soy Lecithin',
        code: 'E322',
        riskLevel: 'Good',
        purpose: 'Emulsifier',
      },
    ],
    positives: ['Rich taste'],
    negatives: ['High in sugar and fat'],
    cautions: ['Contains milk and soy'],
    fullIngredientsList: 'Cocoa, Milk Solids, Sugar, Soy Lecithin',
  },
  {
    id: '8',
    productName: 'Almond Milk',
    brand: 'NutriMilk',
    weight: '1L',
    scanDate: '2025-05-01',
    nutrition: {
      calories: 30,
      protein: 1,
      carbs: 1,
      sugar: 0,
      fat: 2.5,
      saturatedFat: 0.3,
      salt: 0.1,
    },
    ingredients: [
      { name: 'Water', isAdditive: false },
      { name: 'Almonds', isAdditive: false },
    ],
    additives: [],
    positives: ['Low calories', 'Dairy-free'],
    negatives: [],
    cautions: ['Shake before use'],
    fullIngredientsList: 'Water, Almonds, Sea Salt',
  },
  {
    id: '9',
    productName: 'Peanut Butter',
    brand: 'NuttySpread',
    weight: '350g',
    scanDate: '2025-04-30',
    nutrition: {
      calories: 190,
      protein: 8,
      carbs: 6,
      sugar: 1,
      fat: 16,
      saturatedFat: 3,
      salt: 0.6,
    },
    ingredients: [
      { name: 'Peanuts', isAdditive: false },
      { name: 'Salt', isAdditive: false },
    ],
    additives: [],
    positives: ['High protein', 'Healthy fats'],
    negatives: ['High fat'],
    cautions: ['Contains peanuts'],
    fullIngredientsList: 'Peanuts, Salt',
  },
  {
    id: '10',
    productName: 'Frozen Pizza',
    brand: 'QuickMeal',
    weight: '450g',
    scanDate: '2025-04-29',
    nutrition: {
      calories: 950,
      protein: 30,
      carbs: 100,
      sugar: 8,
      fat: 40,
      saturatedFat: 15,
      salt: 2.5,
    },
    ingredients: [
      { name: 'Wheat Flour', isAdditive: false },
      { name: 'Cheese', isAdditive: false },
    ],
    additives: [
      {
        name: 'Sodium Nitrite',
        code: 'E250',
        riskLevel: 'Hazardous',
        purpose: 'Preservative',
        potentialEffects: 'Cancer risk',
      },
    ],
    positives: ['Convenient meal'],
    negatives: ['High fat and salt', 'Contains risky additive'],
    cautions: ['Contains gluten and dairy'],
    fullIngredientsList: 'Wheat Flour, Cheese, Tomato Sauce, Sodium Nitrite',
  },
];
