import { Scan } from '@/types/Scan';

export const mockIngredientsData: Omit<Scan, 'id' | 'scanDate'>[] = [
  {
    productName: 'Organic Granola Cereal',
    brand: 'Nature\'s Path',
    weight: '340g',
    nutrition: {
      calories: 210,
      protein: 5,
      carbs: 36,
      sugar: 8,
      fat: 6,
      saturatedFat: 1,
      salt: 0.2,
    },
    ingredients: [
      { name: 'Rolled oats', isAdditive: false },
      { name: 'Cane sugar', isAdditive: false },
      { name: 'Sunflower oil', isAdditive: false },
      { name: 'Rice', isAdditive: false },
      { name: 'Flaxseeds', isAdditive: false },
      { name: 'Coconut', isAdditive: false },
      { name: 'Sea salt', isAdditive: false },
      { name: 'Vitamin E (mixed tocopherols)', isAdditive: true },
    ],
    additives: [
      {
        name: 'Vitamin E (mixed tocopherols)',
        code: 'E306',
        riskLevel: 'Good',
        purpose: 'Antioxidant',
        description: 'Natural antioxidant that helps prevent oils from going rancid.',
        potentialEffects: 'Generally recognized as safe and beneficial, as vitamin E is an essential nutrient.',
      },
    ],
    positives: [
      'High in fiber',
      'Contains omega-3 fatty acids',
      'No artificial colors or preservatives',
      'Whole grain',
    ],
    negatives: [
      'Contains added sugar',
    ],
    cautions: [],
    fullIngredientsList: 'Rolled oats*, cane sugar*, sunflower oil*, brown rice flour*, flaxseeds*, coconut*, sea salt, mixed tocopherols (vitamin E). *Organic.',
  },
  {
    productName: 'Chocolate Chip Cookies',
    brand: 'Sweet Treats',
    weight: '200g',
    nutrition: {
      calories: 480,
      protein: 6,
      carbs: 68,
      sugar: 38,
      fat: 24,
      saturatedFat: 15,
      salt: 0.7,
    },
    ingredients: [
      { name: 'Wheat flour', isAdditive: false },
      { name: 'Sugar', isAdditive: false },
      { name: 'Butter', isAdditive: false },
      { name: 'Chocolate chips', isAdditive: false },
      { name: 'Eggs', isAdditive: false },
      { name: 'Baking soda', isAdditive: false },
      { name: 'Salt', isAdditive: false },
      { name: 'Artificial flavor', isAdditive: true },
      { name: 'Soy lecithin', isAdditive: true },
      { name: 'BHT', isAdditive: true },
    ],
    additives: [
      {
        name: 'Artificial flavor',
        riskLevel: 'Risky',
        purpose: 'Flavoring',
        description: 'Synthetic compounds used to imitate natural flavors.',
        potentialEffects: 'Some artificial flavors have been linked to behavioral changes in some studies.',
      },
      {
        name: 'Soy lecithin',
        code: 'E322',
        riskLevel: 'No Risk',
        purpose: 'Emulsifier',
        description: 'Derived from soybeans, helps ingredients mix that would otherwise separate.',
        potentialEffects: 'Generally recognized as safe, though allergic reactions possible for those with soy allergies.',
      },
      {
        name: 'BHT',
        code: 'E321',
        riskLevel: 'Hazardous',
        purpose: 'Preservative',
        description: 'Butylated hydroxytoluene prevents oils from oxidizing and becoming rancid.',
        potentialEffects: 'Some studies suggest possible endocrine disruption and potential carcinogenic effects at high doses.',
      },
    ],
    positives: [
      'Good source of energy',
    ],
    negatives: [
      'High in sugar',
      'High in saturated fat',
      'Contains artificial additives',
    ],
    cautions: [
      'Contains common allergens: wheat, dairy, soy, eggs',
      'Contains BHT which may be harmful',
    ],
    fullIngredientsList: 'Wheat flour, sugar, butter, chocolate chips (sugar, chocolate, cocoa butter, soy lecithin, artificial flavor), eggs, baking soda, salt, artificial flavor, BHT.',
  },
  {
    productName: 'Plant-Based Protein Shake',
    brand: 'VegoPower',
    weight: '330ml',
    nutrition: {
      calories: 160,
      protein: 20,
      carbs: 10,
      sugar: 2,
      fat: 3,
      saturatedFat: 0.5,
      salt: 0.3,
    },
    ingredients: [
      { name: 'Filtered water', isAdditive: false },
      { name: 'Pea protein', isAdditive: false },
      { name: 'Coconut milk', isAdditive: false },
      { name: 'Organic cane sugar', isAdditive: false },
      { name: 'Natural flavors', isAdditive: true },
      { name: 'Gellan gum', isAdditive: true },
      { name: 'Stevia leaf extract', isAdditive: true },
    ],
    additives: [
      {
        name: 'Natural flavors',
        riskLevel: 'Good',
        purpose: 'Flavoring',
        description: 'Derived from plant or animal sources to add flavor.',
        potentialEffects: 'Generally recognized as safe, though specific components are often not disclosed.',
      },
      {
        name: 'Gellan gum',
        code: 'E418',
        riskLevel: 'No Risk',
        purpose: 'Stabilizer',
        description: 'Produced by bacterial fermentation, used to thicken and stabilize products.',
        potentialEffects: 'Generally considered safe, may have mild laxative effects in large quantities.',
      },
      {
        name: 'Stevia leaf extract',
        riskLevel: 'No Risk',
        purpose: 'Sweetener',
        description: 'Natural sweetener derived from the stevia plant.',
        potentialEffects: 'Generally recognized as safe and does not affect blood sugar levels.',
      },
    ],
    positives: [
      'High in protein',
      'Low in sugar',
      'Plant-based',
      'No artificial sweeteners',
    ],
    negatives: [],
    cautions: [
      'Contains coconut (allergen)',
    ],
    fullIngredientsList: 'Filtered water, pea protein, coconut milk, organic cane sugar, natural flavors, gellan gum, stevia leaf extract.',
  },
  {
    productName: 'BBQ Flavored Chips',
    brand: 'Tasty Snacks',
    weight: '150g',
    nutrition: {
      calories: 540,
      protein: 6,
      carbs: 55,
      sugar: 6,
      fat: 34,
      saturatedFat: 3.5,
      salt: 1.2,
    },
    ingredients: [
      { name: 'Potatoes', isAdditive: false },
      { name: 'Vegetable oil', isAdditive: false },
      { name: 'BBQ seasoning', isAdditive: false },
      { name: 'Sugar', isAdditive: false },
      { name: 'Salt', isAdditive: false },
      { name: 'Monosodium glutamate', isAdditive: true },
      { name: 'Artificial colors (Red 40, Yellow 6)', isAdditive: true },
      { name: 'Sodium diacetate', isAdditive: true },
      { name: 'TBHQ', isAdditive: true },
    ],
    additives: [
      {
        name: 'Monosodium glutamate',
        code: 'E621',
        riskLevel: 'Risky',
        purpose: 'Flavor enhancer',
        description: 'Used to enhance savory flavors in foods.',
        potentialEffects: 'May cause headaches, flushing, and sweating in some sensitive individuals (MSG symptom complex).',
      },
      {
        name: 'Artificial colors (Red 40, Yellow 6)',
        code: 'E129, E110',
        riskLevel: 'Hazardous',
        purpose: 'Coloring',
        description: 'Synthetic dyes used to color food products.',
        potentialEffects: 'Linked to hyperactivity in children, allergic reactions, and potential carcinogenic effects in some studies.',
      },
      {
        name: 'Sodium diacetate',
        code: 'E262',
        riskLevel: 'No Risk',
        purpose: 'Preservative and flavoring',
        description: 'Salt of acetic acid that acts as a preservative and provides tangy flavor.',
        potentialEffects: 'Generally recognized as safe in moderate amounts.',
      },
      {
        name: 'TBHQ',
        code: 'E319',
        riskLevel: 'Hazardous',
        purpose: 'Preservative',
        description: 'Prevents oxidation of fats and oils.',
        potentialEffects: 'May cause nausea, vomiting, delirium, and has been linked to cancer in some animal studies at high doses.',
      },
    ],
    positives: [],
    negatives: [
      'High in fat',
      'High in sodium',
      'Contains artificial colors',
      'Contains problematic preservatives',
    ],
    cautions: [
      'Contains MSG which may cause sensitivity reactions',
      'Contains artificial colors linked to hyperactivity',
      'Contains TBHQ which may be harmful',
    ],
    fullIngredientsList: 'Potatoes, vegetable oil (sunflower, corn, and/or canola oil), BBQ seasoning (sugar, salt, paprika, tomato powder, onion powder, spices, monosodium glutamate, artificial colors (Red 40, Yellow 6), sodium diacetate, natural and artificial flavors), TBHQ (to preserve freshness).',
  },
  {
    productName: 'Greek Yogurt',
    brand: 'Healthy Dairy',
    weight: '170g',
    nutrition: {
      calories: 120,
      protein: 15,
      carbs: 9,
      sugar: 7,
      fat: 2.5,
      saturatedFat: 1.5,
      salt: 0.1,
    },
    ingredients: [
      { name: 'Cultured pasteurized milk', isAdditive: false },
      { name: 'Cream', isAdditive: false },
      { name: 'Live active cultures', isAdditive: true },
      { name: 'Vitamin D3', isAdditive: true },
    ],
    additives: [
      {
        name: 'Live active cultures',
        riskLevel: 'Good',
        purpose: 'Probiotic',
        description: 'Beneficial bacteria that ferment milk and provide health benefits.',
        potentialEffects: 'Generally beneficial for gut health, digestion, and immune function.',
      },
      {
        name: 'Vitamin D3',
        riskLevel: 'Good',
        purpose: 'Nutrient fortification',
        description: 'Added to increase nutritional value.',
        potentialEffects: 'Essential for calcium absorption and bone health.',
      },
    ],
    positives: [
      'High in protein',
      'Contains probiotics',
      'Good source of calcium',
      'Fortified with vitamin D',
      'Low in fat',
    ],
    negatives: [],
    cautions: [
      'Contains dairy (allergen)',
    ],
    fullIngredientsList: 'Cultured pasteurized milk, cream, live active cultures (S. thermophilus, L. bulgaricus, L. acidophilus, Bifidus, L. casei), vitamin D3.',
  }
];